### ISSUE TITLE
lighting between differnet servers chunks do not update 

### ISSUE THREAD

**Issue by alaajel** [PureGero/MultiPaper#213]
https://user-images.githubusercontent.com/34905970/178288162-09f4f181-de0e-4c13-a46c-e8622b456c63.mp4

**Comment by PureGero** [comment]
Seems to be working for me. Does it start working if you increase the delay on the repeaters? Can you send the /version and your multipaper.yml?

**Comment by ham1255** [comment]
forgot add the yml file
```
master-connection:
  advertise-to-built-in-proxy: true
  master-address: localhost:20000
  my-name: server-2
optimizations:
  disable-safety-redstone-chunk-lock: false
  dont-save-just-for-lighting-updates: false
  reduce-player-position-updates-in-unloaded-chunks: false
  ticks-per-inactive-entity-tracking: 1
  use-event-based-io: true
peer-connection:
  compression-threshold: 0
  consolidation-delay: 0
sync-settings:
  files:
    files-to-not-sync:
    - plugins
    files-to-only-upload-on-server-stop:
    - plugins/MyPluginDirectory/my_big_database.db
    files-to-sync-in-real-time:
    - plugins/MyPluginDirectory/userdata
    files-to-sync-on-startup:
    - myconfigfile.yml
    - plugins/MyPlugin.jar
    log-file-syncs: true
  sync-entity-ids: true
  sync-json-files: true
  sync-permissions: false
  sync-scoreboards: true
  use-local-player-count-for-server-is-full-kick: false

```
anyways `/paper fixlight` did fix the issue and light started to update perfectly normal but why would lighting on chunk stop ticking?
